Parameters:    
  LifecyclePolicyText:
    Type: String
    Default: >
      {
        "rules": [
          {
            "rulePriority": 1,
            "description": "only keep the previous image",
            "selection": {
                "tagStatus": "untagged",
                "countType": "imageCountMoreThan",
                "countNumber": 2
            },
            "action": {
                "type": "expire"
            }
          }
        ]
      }
  AppName:
    Type: String

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      LifecyclePolicy:
        LifecyclePolicyText: !Ref LifecyclePolicyText
      RepositoryName: !Ref AppName

Outputs:    
  Arn:
    Value: !GetAtt ECRRepository.Arn