Parameters:
  OpsEmailAddress:
    Type: String

Resources:
  SNSTopic:
      Type: AWS::SNS::Topic
      Properties:
          Subscription:
              -   Endpoint: !Ref OpsEmailAddress
                  Protocol: email

  SnsPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties: 
      Topics: [!Ref SNSTopic]         
      PolicyDocument:
        Statement:
          - Sid: AllowServices
            Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action: 'sns:Publish'
            Resource:
              - !Ref SNSTopic

Outputs:
  SNSTopicName:
    Value: !GetAtt SNSTopic.TopicName
    Export:
      Name: !Sub "${AWS::StackName}-sns-topic-name"
  SNSTopicArn:
    Value: !GetAtt SNSTopic.TopicArn
    Export:
      Name: !Sub "${AWS::StackName}-sns-topic-arn"